from __future__ import annotations

import json
import os
import re
import tempfile
from pathlib import Path

from .team import ROLE_DEFINITIONS, ROLE_REGISTRY_METADATA, RoleDefinition

REQUIRED_SKILL_HEADINGS = {
    "## Contract",
    "## Workflow",
    "## Required output",
    "## Stop and escalate",
    "## Handoff",
}
UNSAFE_SKILL_PATTERNS = ("rm -rf", "git reset --hard", "git checkout --", "OPENROUTER_API_KEY=")


def scaffold_team(target: str | Path, *, force: bool = False) -> tuple[Path, ...]:
    """Install portable role contracts after collision and path-safety preflight."""
    root = Path(target).expanduser().resolve()
    if root.exists() and not root.is_dir():
        raise ValueError(f"team target must be a directory: {root}")
    files: dict[Path, str] = {
        root / ".ai" / "TEAM.md": _render_team_readme(),
        root / ".ai" / "team.json": _render_registry(),
    }
    for definition in ROLE_DEFINITIONS:
        skill_root = root / ".agents" / "skills" / definition.skill_name
        files[skill_root / "SKILL.md"] = _render_skill(definition)
        files[skill_root / "agents" / "openai.yaml"] = _render_openai_yaml(definition)

    escaped = tuple(path for path in files if not _is_within_root(root, path))
    if escaped:
        names = ", ".join(str(path) for path in escaped)
        raise ValueError(f"team destinations must stay inside the target project: {names}")

    blocked_parents = tuple(
        ancestor
        for path in files
        if (ancestor := _blocking_ancestor(root, path)) is not None
    )
    if blocked_parents:
        names = ", ".join(
            str(path.relative_to(root)) for path in dict.fromkeys(blocked_parents)
        )
        raise ValueError(f"team destination parent is not a directory: {names}")

    conflicts = tuple(path for path in files if path.exists())
    if conflicts and not force:
        names = ", ".join(str(path.relative_to(root)) for path in conflicts)
        raise FileExistsError(f"refusing to overwrite existing team files: {names}")
    invalid_leaves = tuple(path for path in conflicts if not path.is_file())
    if invalid_leaves:
        names = ", ".join(str(path.relative_to(root)) for path in invalid_leaves)
        raise ValueError(f"generated team destinations must be regular files: {names}")

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(path, content)
    return tuple(files)


def _is_within_root(root: Path, path: Path) -> bool:
    try:
        path.resolve().relative_to(root)
    except ValueError:
        return False
    return True


def _blocking_ancestor(root: Path, path: Path) -> Path | None:
    candidate = path.parent
    while candidate != root:
        if candidate.exists() and not candidate.is_dir():
            return candidate
        candidate = candidate.parent
    return None


def _atomic_write(path: Path, content: str) -> None:
    descriptor, temporary_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _render_registry() -> str:
    payload = {"schema_version": 1, "roles": _expected_registry_roles()}
    return json.dumps(payload, indent=2) + "\n"


def _expected_registry_roles() -> list[dict[str, object]]:
    return [
        {
            "id": ROLE_REGISTRY_METADATA[definition.role][0],
            "skill": definition.skill_name,
            "team": ROLE_REGISTRY_METADATA[definition.role][1],
            "authority": definition.mutation_authority,
            "next": list(ROLE_REGISTRY_METADATA[definition.role][2]),
        }
        for definition in ROLE_DEFINITIONS
    ]


def _render_team_readme() -> str:
    return """# Project agent team

This project uses explicit specialist roles generated by `ai-gateway-team init`. The Python
planner selects only the roles needed for a task. Agent runtimes are supplied by the host project.

Workflow: Team Lead -> discovery/design -> Builder -> independent Reviewer/QA/Safety gates ->
Documentation/Marketer -> explicitly authorized Release.

Rules:

- Keep one accountable owner per artifact.
- Reviewer, QA, and Safety cannot certify their own implementation.
- Stop downstream work when a required gate fails.
- Use deterministic planning by default; provider calls belong in registered handlers.
- Never publish, deploy, or mutate external systems without explicit authorization.
- Use an LLM council only for high-stakes, ambiguous product or research decisions.
"""


def _render_skill(definition: RoleDefinition) -> str:
    return f"""---
name: {definition.skill_name}
description: {definition.purpose}
---

# {definition.display_name}

## Purpose

{definition.purpose}

## Authority

{definition.mutation_authority}. Stay inside this authority and report any required expansion.

## Contract

Stay within the declared authority. Keep evidence, decisions, reasons, and gate status observable.
Do not expose secrets, private prompts, credentials, or unredacted production traces.

## Workflow

1. Read the project instructions, active task contract, relevant source, and tests.
2. Confirm scope, authority, dependencies, and the required gate.
3. Perform only the bounded work assigned to this role.
4. Record evidence, checks, risks, and the exact next owner.

## Required output

Return a concise status, summary, artifacts changed or inspected, evidence, unresolved risks, gate
result, and recommended next role.

## Stop and escalate

Stop when authority is missing, scope would materially expand, required evidence is unavailable, or
a safety or certification gate fails. Never waive another role's independent certification.

## Handoff

Hand off to one explicit next owner from the project team registry. Preserve failed gates and open
risks rather than silently continuing downstream work.
"""


def _render_openai_yaml(definition: RoleDefinition) -> str:
    short = f"Apply the {definition.display_name} project role contract"
    return f'''interface:
  display_name: "{definition.display_name}"
  short_description: "{short}"
  default_prompt: "Use ${definition.skill_name} for this bounded project task."
'''


def validate_scaffold(target: str | Path) -> tuple[str, ...]:
    root = Path(target).expanduser().resolve()
    errors: list[str] = []
    registry_path = root / ".ai" / "team.json"
    try:
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return (f".ai/team.json: {error}",)
    if not isinstance(registry, dict):
        return (".ai/team.json: root must be a JSON object",)
    roles = registry.get("roles", [])
    if registry.get("schema_version") != 1:
        errors.append(".ai/team.json has an unsupported schema_version")
    if roles != _expected_registry_roles():
        errors.append(".ai/team.json role metadata does not match the built-in roster")
    expected_skills = {definition.skill_name for definition in ROLE_DEFINITIONS}
    skills_root = root / ".agents" / "skills"
    try:
        discovered = {path.name for path in skills_root.iterdir() if path.is_dir()}
    except OSError as error:
        errors.append(f".agents/skills: {error}")
        discovered = set()
    if discovered != expected_skills:
        errors.append("skill folders and .ai/team.json entries are not one-to-one")
    if not (root / ".ai" / "TEAM.md").is_file():
        errors.append(".ai/TEAM.md is missing")
    for definition in ROLE_DEFINITIONS:
        skill_root = root / ".agents" / "skills" / definition.skill_name
        skill_path = skill_root / "SKILL.md"
        try:
            text = skill_path.read_text(encoding="utf-8")
        except OSError as error:
            errors.append(f"{definition.skill_name}/SKILL.md: {error}")
            continue
        match = re.fullmatch(r"---\n(.*?)\n---\n(.*)", text, re.DOTALL)
        if not match:
            errors.append(f"{definition.skill_name}: missing anchored YAML frontmatter")
            continue
        metadata: dict[str, str] = {}
        malformed = False
        for line in match.group(1).splitlines():
            if ":" not in line:
                malformed = True
                break
            key, value = line.split(":", 1)
            metadata[key.strip()] = value.strip().strip('"')
        if malformed or set(metadata) != {"name", "description"}:
            errors.append(f"{definition.skill_name}: invalid frontmatter fields")
        if metadata.get("name") != definition.skill_name:
            errors.append(f"{definition.skill_name}: folder and frontmatter names differ")
        description = metadata.get("description", "")
        if not description or len(description) > 1024 or "<" in description or ">" in description:
            errors.append(f"{definition.skill_name}: description is empty or invalid")
        body = match.group(2)
        if "TODO" in body or "[TODO" in body:
            errors.append(f"{definition.skill_name}: unresolved template placeholder")
        if len(body.splitlines()) > 500:
            errors.append(f"{definition.skill_name}: SKILL.md exceeds 500 body lines")
        headings = set(re.findall(r"^## .+$", body, re.MULTILINE))
        missing = sorted(REQUIRED_SKILL_HEADINGS - headings)
        if missing:
            errors.append(f"{definition.skill_name}: missing headings {', '.join(missing)}")
        for pattern in UNSAFE_SKILL_PATTERNS:
            if pattern in body:
                errors.append(f"{definition.skill_name}: forbidden unsafe pattern {pattern!r}")
        yaml_path = skill_root / "agents" / "openai.yaml"
        try:
            yaml = yaml_path.read_text(encoding="utf-8")
        except OSError as error:
            errors.append(f"{definition.skill_name}/agents/openai.yaml: {error}")
            continue
        for field in ("display_name", "short_description", "default_prompt"):
            if not re.search(rf'^\s*{field}:\s*"[^"]+"\s*$', yaml, re.MULTILINE):
                errors.append(f"{definition.skill_name}: openai.yaml lacks quoted {field}")
        short = re.search(r'^\s*short_description:\s*"([^"]+)"', yaml, re.MULTILINE)
        if short and not 25 <= len(short.group(1)) <= 64:
            errors.append(
                f"{definition.skill_name}: short_description must contain 25-64 characters"
            )
        if f"${definition.skill_name}" not in yaml:
            errors.append(f"{definition.skill_name}: default_prompt does not invoke the skill")
    return tuple(sorted(errors))
