"""Dependency-free browser console for the optional FastAPI transport."""

CONSOLE_HTML = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Routing Gateway console</title><style>body{font:16px system-ui;max-width:920px;margin:2rem auto;padding:0 1rem;color:#18212b}textarea,select,input,button{font:inherit}textarea{width:100%;min-height:8rem}label{display:block;font-weight:600;margin-top:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem}button{margin-top:1rem;padding:.7rem 1rem}pre{background:#f2f4f7;padding:1rem;overflow:auto}.note{background:#eef6ff;border-left:4px solid #1769aa;padding:.8rem}</style></head><body>
<h1>AI Routing Gateway console</h1><p class="note">Runs the deterministic offline router by default. Execution is off so this page only explains the selected route.</p>
<label for="prompt">Prompt</label><textarea id="prompt">Compare two safe deployment strategies for a small API.</textarea>
<div class="grid"><label>Optimization<select id="optimization"><option>balanced</option><option>cost</option><option>latency</option><option>quality</option></select></label><label>Maximum cost (USD)<input id="cost" type="number" min="0" step="0.001" placeholder="optional"></label><label>Maximum latency (ms)<input id="latency" type="number" min="0" placeholder="optional"></label></div>
<button id="route">Explain route</button><button id="capabilities">Show capabilities</button><pre id="result" aria-live="polite">Ready.</pre>
<script>const out=document.querySelector('#result');async function show(response){const body=await response.json();out.textContent=JSON.stringify({status:response.status,...body},null,2)}
document.querySelector('#route').onclick=async()=>{const value=id=>document.querySelector(id).value;const payload={prompt:value('#prompt'),execute:false,optimization:value('#optimization')};if(value('#cost'))payload.max_cost_usd=Number(value('#cost'));if(value('#latency'))payload.max_latency_ms=Number(value('#latency'));try{await show(await fetch('/v1/route',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}))}catch(error){out.textContent=String(error)}};
document.querySelector('#capabilities').onclick=async()=>{try{await show(await fetch('/v1/capabilities'))}catch(error){out.textContent=String(error)}};</script></body></html>"""
